version: '3'
services:
  ovpn_server:
    image: ubuntu:14.04
    command: "/bin/bash"
    stdin_open: true
    tty: true  
    container_name: "ovpn_server"
    restart: "no"
    privileged: true
    volumes:
      - ./openvpnconfig:/etc/openvpn
    networks:
      - overlay
  ovpn_client_1:
    image: ubuntu:14.04
    stdin_open: true # docker run -i
    privileged: true
    tty: true  
    command: "/bin/bash"
    container_name: "ovpn_client_1"
    volumes:
      - ./client1:/home
    restart: "no"
    networks:
      - overlay
  ovpn_client_2:
    image: ubuntu:14.04
    privileged: true
    stdin_open: true # docker run -i
    tty: true
    volumes:
      - ./client2:/home
    command: "/bin/bash"
    container_name: "ovpn_client_2"
    restart: "no"
    networks:
      - overlay

  ovpn_client_3:
    image: ubuntu:14.04
    privileged: true
    stdin_open: true # docker run -i
    tty: true
    volumes:
      - ./client3:/home
    command: "/bin/bash"
    container_name: "ovpn_client_3"
    restart: "no"
    networks:
      - overlay

  ovpn_client_4:
    image: ubuntu:14.04
    privileged: true
    stdin_open: true # docker run -i
    tty: true
    volumes:
      - ./client4:/home
    command: "/bin/bash"
    container_name: "ovpn_client_4"
    restart: "no"
    networks:
      - overlay


networks:
  overlay:
